/* ============================================================
   PLAYER SPRITE: the drawn character that walks the town (replaces the round emoji badge)
   ============================================================
   The art is assets/player-art.js (PLAYER_ART, generated by scripts/build_player_art.py from the drawings in assets/player/<id>/, one folder per character).
   Each view (down, up, left, and right when it has its own drawing) is three stacked layers: the body and the two feet. While
   `.ent.player.walking` is on (js/town-render-weather.js adds and removes it), css/latest.css bobs the body and lifts one foot
   per step. Facing is worked out from the last step in positionPlayer(); it is not saved, a fresh load faces down.
   A missing right view is the left view mirrored with CSS. If PLAYER_ART is absent the old emoji badge is used instead. */
let plFace = 'down';

// `state.character.drawn` is the avatar choice: the id of a drawn character ('first', 'don', ...; PLAYER_ART.order), or false for an emoji look.
// undefined, true and an id that no longer exists all mean the first drawn character, so older saves keep the look they already had.
function playerSpriteReady() { return typeof PLAYER_ART !== 'undefined' && !!PLAYER_ART && !!PLAYER_ART.chars && PLAYER_ART.order.some(id => PLAYER_ART.chars[id] && PLAYER_ART.chars[id].views.down); }
function playerCharId() {
  if (!playerSpriteReady() || state.character.drawn === false) return null;
  const d = state.character.drawn;
  return typeof d === 'string' && PLAYER_ART.chars[d] ? d : PLAYER_ART.order.find(id => PLAYER_ART.chars[id]);
}
function playerDrawn() { return !!playerCharId(); }
function playerArt() { const id = playerCharId(); return id ? PLAYER_ART.chars[id] : null; }

function playerSpriteHTML() {
  const art = playerArt();
  if (!art) return '<div class="pl-badge"></div>';
  const views = Object.keys(art.views).map(k => {
    const v = art.views[k];
    return `<div class="pl-view" data-v="${k}"><img class="pl-leg l" src="${v.legL}" alt="" draggable="false"><img class="pl-leg r" src="${v.legR}" alt="" draggable="false"><img class="pl-body" src="${v.upper}" alt="" draggable="false"></div>`;
  }).join('');
  return `<div class="pl-sprite" data-view="down" data-char="${playerCharId()}">${views}</div>`;
}

// Turn the character to face where the last step went. Teleports (a new district) are bigger than one tile and keep the old facing.
function playerFaceFromMove(from, to) {
  if (!from || !to) return;
  const dx = to.x - from.x, dy = to.y - from.y;
  if (!dx && !dy || Math.abs(dx) + Math.abs(dy) > 2) return;
  plFace = Math.abs(dx) > Math.abs(dy) ? (dx > 0 ? 'right' : 'left') : (dy > 0 ? 'down' : 'up');
}

function applyPlayerSprite(el, character) {
  const spr = el && el.querySelector('.pl-sprite');
  if (!spr) return;
  const art = playerArt(), views = art.views;
  const own = plFace === 'right' && views.right;      // a real right-facing drawing, otherwise left mirrored
  const key = plFace === 'right' ? (views.right ? 'right' : 'left') : plFace;
  if (spr.dataset.view !== key) spr.dataset.view = key;
  const flip = plFace === 'right' && !own ? '1' : '';
  if (spr.dataset.flip !== flip) spr.dataset.flip = flip;
  spr.dataset.accessory = character.accessory || '';
  el.style.setProperty('--pl-leg-top', art.meta.legTop + '%');
  el.style.setProperty('--pl-aspect', art.meta.aspect);
  el.style.setProperty('--pl-step', STEP_MS + 'ms');  // a walk with your companion is slower, so the stride is too
}

// ---- the round avatar portraits (HUD, battle, Character tab, the picker) show the face crop instead of the emoji ----
function setAvFace(el, character) {
  if (!el) return;
  if (!playerDrawn()) { el.textContent = character.emoji; return; }
  el.textContent = '';
  const img = document.createElement('img'); img.className = 'av-face'; img.src = playerArt().face; img.alt = ''; img.draggable = false;
  el.appendChild(img);
}
function avFaceHTML(character) { return playerDrawn() ? `<img class="av-face" src="${playerArt().face}" alt="" draggable="false">` : escapeHtml(character.emoji); }

// The first swatches in every avatar row: your drawn characters, same size as the emoji swatches. Free, always unlocked.
function drawnAvatarSwatch(id) {
  const el = document.createElement('div'), ch = PLAYER_ART.chars[id];
  el.className = 'emoji-swatch shop-swatch drawn-swatch' + (playerCharId() === id ? ' active' : '');
  el.title = ch.name; el.setAttribute('aria-label', ch.name);
  el.innerHTML = `<img class="av-face" src="${ch.face}" alt="" draggable="false">`;
  el.addEventListener('click', () => {
    ensureAudio(); sfx('nav'); buzz(HAP.tap);
    state.character.drawn = id;
    saveState(); updateHud(); renderTown(); renderCustomize(); if (typeof renderCharacterTab === 'function') renderCharacterTab();
  });
  return el;
}
function drawnAvatarSwatches() { return playerSpriteReady() ? PLAYER_ART.order.filter(id => PLAYER_ART.chars[id]).map(drawnAvatarSwatch) : []; }
