/* ============================================================
   PLAYER SPRITE: the drawn character that walks the town (replaces the round emoji badge)
   ============================================================
   The art is assets/player-art.js (PLAYER_ART, generated by scripts/build_player_art.py from the drawings in assets/player/).
   Each view (down, up, left, and right when it has its own drawing) is three stacked layers: the body and the two feet. While
   `.ent.player.walking` is on (js/town-render-weather.js adds and removes it), css/latest.css bobs the body and lifts one foot
   per step. Facing is worked out from the last step in positionPlayer(); it is not saved, a fresh load faces down.
   A missing right view is the left view mirrored with CSS. If PLAYER_ART is absent the old emoji badge is used instead. */
let plFace = 'down';

function playerSpriteReady() { return typeof PLAYER_ART !== 'undefined' && PLAYER_ART && PLAYER_ART.views && PLAYER_ART.views.down; }

function playerSpriteHTML() {
  if (!playerSpriteReady()) return '<div class="pl-badge"></div>';
  const views = Object.keys(PLAYER_ART.views).map(k => {
    const v = PLAYER_ART.views[k];
    return `<div class="pl-view" data-v="${k}"><img class="pl-leg l" src="${v.legL}" alt="" draggable="false"><img class="pl-leg r" src="${v.legR}" alt="" draggable="false"><img class="pl-body" src="${v.upper}" alt="" draggable="false"></div>`;
  }).join('');
  return `<div class="pl-sprite" data-view="down">${views}</div>`;
}

// Turn the character to face where the last step went. Teleports (a new district) are bigger than one tile and keep the old facing.
function playerFaceFromMove(from, to) {
  if (!from || !to) return;
  const dx = to.x - from.x, dy = to.y - from.y;
  if (!dx && !dy || Math.abs(dx) + Math.abs(dy) > 2) return;
  plFace = Math.abs(dx) > Math.abs(dy) ? (dx > 0 ? 'right' : 'left') : (dy > 0 ? 'down' : 'up');
}

function applyPlayerSprite(el, character) {
  const spr = el && el.querySelector('.pl-sprite');
  if (!spr) return;
  const views = PLAYER_ART.views;
  const own = plFace === 'right' && views.right;      // a real right-facing drawing, otherwise left mirrored
  const key = plFace === 'right' ? (views.right ? 'right' : 'left') : plFace;
  if (spr.dataset.view !== key) spr.dataset.view = key;
  const flip = plFace === 'right' && !own ? '1' : '';
  if (spr.dataset.flip !== flip) spr.dataset.flip = flip;
  spr.dataset.accessory = character.accessory || '';
  el.style.setProperty('--pl-leg-top', PLAYER_ART.meta.legTop + '%');
  el.style.setProperty('--pl-aspect', PLAYER_ART.meta.aspect);
  el.style.setProperty('--pl-step', STEP_MS + 'ms');  // a walk with your companion is slower, so the stride is too
}
